### ISSUE TITLE
add labels to form elements and connect error messages

### ISSUE THREAD

**Issue by lisahns** [fac25/alex-abby-manoela-suraj-database-B#26]
great website!

it's important to add labels to form elements for users of assistive technology, like a screen reader.

Additionally, you could think of associating the input error message with the input it corresponds to by using `aria-describedby`, which helps users using assistive technology understand which error relates to which input.
you can read more here: https://www.a11yproject.com/checklist/#associate-input-error-messaging-with-the-input-it-corresponds-to

**Comment by yassienAbdillahi** [comment]
On the same point, the various inputs in the form do not have id attributes. This is what would bind the labels to their respective inputs. See [this w3 schools article](https://www.w3schools.com/html/html_forms.asp) for more details

**Comment by SurPun** [comment]
Thank you lisa & yassien, Completed in [40fd97f]
