### ISSUE TITLE
User consideration

### ISSUE THREAD

**Issue by patdel0** [fac25/alex-abby-manoela-suraj-database-B#27]
Just passing by to commend you on the attention to detail, by capitalizing the user input in the names fields.

https://github.com/fac25/alex-abby-manoela-suraj-database-B/blob/7bbbc6ed875bf5fe650ba1459c052417af2966ba/src/templates.js#L64-L70

**Comment by lisahns** [comment]
+1

**Comment by modanova** [comment]
Thanks!
