### ISSUE TITLE
Use early returns to avoid nested conditions

### ISSUE THREAD

**Issue by ivan-unfolds** [fac25/alex-abby-manoela-suraj-database-B#38]
This one is more of a style tip so feel free to ignore, but I like using early returns to avoid nesting:

more info here: https://dev.to/yvonnickfrin/devtips-use-early-returns-to-avoid-nested-conditions-4i51

and here's the relevant bit in your codebase: https://github.com/fac25/alex-abby-manoela-suraj-database-B/blob/main/src/server.js#L44

**Comment by SurPun** [comment]
Thank you Ivan, we have made changes to it.
