### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by Abbbyccc** [fac25/alex-abby-manoela-suraj-database-B#5]

**Comment by SurPun** [comment]
- [x] Server is connected & post/display
- [x] ListMusic Function successfully retrieves data
- [x]  Test four is failing, username is undefined @Abbbyccc @SurPun @modanova @AlexPD93 .

**Comment by SurPun** [comment]
Completed in 5be668d20ee8dc0cda41e12ff980b2eeebcbc88f & 2f748f962001abb929b735a9c7e4111ec5575853
